import pandas as pd
from datetime import date

def get_asset_checks():
    """Returns a list of Asset DQ check definitions."""
    today = pd.Timestamp(date.today())

    checks = [
        # ======================================================================
        # ASSET GROUPS & CONFIGURATION (DQ-AG-)
        # ======================================================================
        ('DQ-AG-C01', 19, 'Asset Groups', 'Completeness', 'Critical',
         'asset_group is null or blank', 
         'Primary key violation.',
         'Populate asset_group.', 'asset_groups', None, 
         'asset_group IS NULL',
         lambda df: df['asset_group'].isna() | (df['asset_group'] == '')),

        ('DQ-AG-C02', 19, 'Asset Groups', 'Completeness', 'High',
         'description missing for active group', 
         'Mandatory master data missing.',
         'Populate description.', 'asset_groups', None, 
         'grp_status = N AND description IS NULL',
         lambda df: (df['grp_status'] == 'N') & (df['description'].isna() | (df['description'] == ''))),

        ('DQ-AG-V01', 19, 'Asset Groups', 'Validity', 'Critical',
         'depr_method invalid at group level', 
         'Configuration error inherited by assets.',
         'Correct depr_method (LIN, BAL, EXP, SYD).', 'asset_groups', None, 
         'depr_method NOT IN (LIN, BAL, EXP, SYD)',
         lambda df: ~df['depr_method'].isin(['LIN', 'BAL', 'EXP', 'SYD'])),

        ('DQ-AG-V04', 19, 'Asset Groups', 'Validity', 'High',
         'depr_percent exceeds 100%', 
         'Invalid depreciation rate.',
         'Correct depr_percent.', 'asset_groups', None, 
         'depr_percent > 100',
         lambda df: pd.to_numeric(df['depr_percent'], errors='coerce') > 100),

        ('DQ-AG-V05', 19, 'Asset Groups', 'Timeliness', 'High',
         'lifetime <= 0 for LIN/SYD method', 
         'Useful life must be positive.',
         'Correct lifetime.', 'asset_groups', None, 
         'lifetime <= 0 AND method IN (LIN, SYD)',
         lambda df: (df['depr_method'].isin(['LIN', 'SYD'])) & (pd.to_numeric(df['lifetime'], errors='coerce') <= 0)),

        ('DQ-AG-K01', 19, 'Asset Groups', 'Consistency', 'High',
         'Active book on inactive group', 
         'Contradictory configuration.',
         'Align grp_status and book_status.', 'asset_groups', None, 
         'book_status = N AND grp_status != N',
         lambda df: (df['book_status'] == 'N') & (df['grp_status'] != 'N')),

        ('DQ-AG-D02', 19, 'Asset Groups', 'Uniqueness', 'Medium',
         'Duplicate group description', 
         'Potential naming collision.',
         'Review descriptions.', 'asset_groups', None, 
         'COUNT(*) OVER(PARTITION BY description) > 1',
         lambda df: df.duplicated(subset=['house', 'description'], keep=False)),

        ('DQ-AG-X01', 19, 'Asset Master', 'Referential Integrity', 'Critical',
         'Asset assigned to non-existent group', 
         'Broken link to configuration.',
         'Correct asset_group in master.', 'asset_master', 'asset_groups', 
         'asset_master.asset_group NOT IN asset_groups',
         lambda df, frames: ~df['asset_group'].isin(frames.get('asset_groups', pd.DataFrame())['asset_group']) if 'asset_groups' in frames else pd.Series(False, index=df.index)),

        ('DQ-AG-X03', 19, 'Asset Depreciation', 'Consistency', 'High',
         'Asset method differs from Group default', 
         'Individual asset override detected. Will require manual migration effort.',
         'Verify if override is intentional.', 'asset_depreciation', 'asset_groups', 
         'asset.depr_method != group.depr_method',
         lambda df, frames: df['asset_id'].isin(
             df.merge(
                 frames.get('asset_master', pd.DataFrame())[['house', 'asset_id', 'asset_group']], 
                 on=['house', 'asset_id'], how='left'
             ).merge(
                 frames.get('asset_groups', pd.DataFrame())[['house', 'asset_group', 'depr_method']], 
                 on=['house', 'asset_group'], how='inner', suffixes=('', '_grp')
             ).query('depr_method != depr_method_grp')['asset_id']
         ) if 'asset_groups' in frames and 'asset_master' in frames else pd.Series(False, index=df.index)),

        ('DQ-AG-X04', 19, 'Asset Depreciation', 'Consistency', 'Medium',
         'Asset lifetime differs from Group default', 
         'Useful life override detected.',
         'Verify if override is intentional.', 'asset_depreciation', 'asset_groups', 
         'asset.lifetime != group.lifetime',
         lambda df, frames: df['asset_id'].isin(
             df.merge(
                 frames.get('asset_master', pd.DataFrame())[['house', 'asset_id', 'asset_group']], 
                 on=['house', 'asset_id'], how='left'
             ).merge(
                 frames.get('asset_groups', pd.DataFrame())[['house', 'asset_group', 'lifetime']], 
                 on=['house', 'asset_group'], how='inner', suffixes=('', '_grp')
             ).query('lifetime != lifetime_grp')['asset_id']
         ) if 'asset_groups' in frames and 'asset_master' in frames else pd.Series(False, index=df.index)),

        # ======================================================================
        # ASSET MASTER (DQ-AM-)
        # ======================================================================
        ('DQ-AM-C01', 19, 'Asset Master', 'Completeness', 'Critical', 
         'asset_id is null or blank', 
         'No asset can exist without a primary key. Blocking for migration.',
         'Populate asset_id.', 'asset_master', None, 
         'asset_id IS NULL OR asset_id = ""',
         lambda df: df['asset_id'].isna() | (df['asset_id'] == '')),
         
        ('DQ-AM-C02', 19, 'Asset Master', 'Completeness', 'High',
         'description is null or blank for active asset', 
         'Active assets must have a human-readable identifier.',
         'Populate description.', 'asset_master', None, 
         'description IS NULL',
         lambda df: df['description'].isna() | (df['description'] == '')),
         
        ('DQ-AM-C03', 19, 'Asset Master', 'Completeness', 'High',
         'asset_group is null or blank for active asset', 
         'Drives depreciation defaults and GL mapping.',
         'Populate asset_group.', 'asset_master', None, 
         'asset_group IS NULL',
         lambda df: df['asset_group'].isna() | (df['asset_group'] == '')),
         
        ('DQ-AM-C04', 19, 'Asset Master', 'Completeness', 'High',
         'date_from is null for active asset', 
         'Ownership start date must be present.',
         'Populate date_from.', 'asset_master', None, 
         'date_from IS NULL',
         lambda df: df['date_from'].isna()),
         
        ('DQ-AM-C05', 19, 'Asset Master', 'Completeness', 'High',
         'org_amount is null or zero for capitalised active asset', 
         'Capitalised assets must have a cost.',
         'Populate org_amount.', 'asset_master', None, 
         'org_amount <= 0 AND cap_date_from IS NOT NULL',
         lambda df: (pd.to_numeric(df['org_amount'], errors='coerce').fillna(0) <= 0) & df['cap_date_from'].notna()),

        ('DQ-AM-C06', 19, 'Asset Master', 'Completeness', 'Medium',
         'cap_date_from is null where cap_flag is expected to be true', 
         'Capitalised assets need a capitalisation date.',
         'Populate cap_date_from.', 'asset_master', 'asset_depreciation', 
         'cap_date_from IS NULL AND cap_flag=1',
         lambda df, frames: df['cap_date_from'].isna() & df['asset_id'].isin(frames.get('asset_depreciation', pd.DataFrame()).query('cap_flag == 1')['asset_id']) if 'asset_depreciation' in frames else pd.Series(False, index=df.index)),

        ('DQ-AM-C07', 19, 'Asset Master', 'Completeness', 'Low',
         'ins_amount is null or zero for active asset', 
         'Completeness gap worth surfacing.',
         'Review ins_amount.', 'asset_master', None, 
         'ins_amount <= 0',
         lambda df: pd.to_numeric(df['ins_amount'], errors='coerce').fillna(0) <= 0),

        ('DQ-AM-V01', 19, 'Asset Master', 'Validity', 'Critical',
         'status not in valid list', 
         'Unexpected status code.',
         'Correct status.', 'asset_master', None, 
         'status NOT IN (N,P,C,T)',
         lambda df: ~df['status'].isin(['N', 'P', 'C', 'T'])),

        ('DQ-AM-V02', 19, 'Asset Master', 'Validity', 'High',
         'wf_state not in valid list', 
         'Value outside documented valuelist.',
         'Correct wf_state.', 'asset_master', None, 
         'wf_state NOT IN ("",N,T,A,C,R,U,W,X)',
         lambda df: ~df['wf_state'].fillna('').isin(['', 'N', 'T', 'A', 'C', 'R', 'U', 'W', 'X'])),

        ('DQ-AM-V03', 19, 'Asset Master', 'Validity', 'High',
         'org_amount is negative', 
         'Negative original cost is not valid.',
         'Correct org_amount.', 'asset_master', None, 
         'org_amount < 0',
         lambda df: pd.to_numeric(df['org_amount'], errors='coerce').fillna(0) < 0),

        ('DQ-AM-V04', 19, 'Asset Master', 'Timeliness', 'High',
         'date_from is after date_to', 
         'Ownership cannot end before it begins.',
         'Correct dates.', 'asset_master', None, 
         'date_from > date_to',
         lambda df: pd.to_datetime(df['date_from'], errors='coerce').notna() & pd.to_datetime(df['date_to'], errors='coerce').notna() & (pd.to_datetime(df['date_from'], errors='coerce') > pd.to_datetime(df['date_to'], errors='coerce'))),

        ('DQ-AM-V05', 19, 'Asset Master', 'Timeliness', 'Medium',
         'cap_date_from is before date_from', 
         'Asset cannot be capitalised before ownership started.',
         'Correct dates.', 'asset_master', None, 
         'cap_date_from < date_from',
         lambda df: pd.to_datetime(df['cap_date_from'], errors='coerce').notna() & pd.to_datetime(df['date_from'], errors='coerce').notna() & (pd.to_datetime(df['cap_date_from'], errors='coerce') < pd.to_datetime(df['date_from'], errors='coerce'))),

        ('DQ-AM-V06', 19, 'Asset Master', 'Timeliness', 'Medium',
         'org_amt_date differs from cap_date_from by > 365 days', 
         'Cost recorded significantly different to capitalisation.',
         'Review dates.', 'asset_master', None, 
         'ABS(org_amt_date - cap_date_from) > 365',
         lambda df: pd.to_datetime(df['org_amt_date'], errors='coerce').notna() & pd.to_datetime(df['cap_date_from'], errors='coerce').notna() & ((pd.to_datetime(df['org_amt_date'], errors='coerce') - pd.to_datetime(df['cap_date_from'], errors='coerce')).dt.days.abs() > 365)),

        ('DQ-AM-T01', 19, 'Asset Master', 'Timeliness', 'Medium',
         'last_update is in the future', 
         'Indicates a system clock or data entry error.',
         'Correct date.', 'asset_master', None, 
         'last_update > TODAY',
         lambda df: pd.to_datetime(df['last_update'], errors='coerce').notna() & (pd.to_datetime(df['last_update'], errors='coerce') > today)),

        ('DQ-AM-K01', 19, 'Asset Master', 'Consistency', 'High',
         'date_to is populated but status is active', 
         'Asset shows as active but ownership ended.',
         'Review status.', 'asset_master', None, 
         'date_to IS NOT NULL AND status="N"',
         lambda df: df['date_to'].notna() & (df['status'] == 'N')),

        ('DQ-AM-K02', 19, 'Asset Master', 'Consistency', 'High',
         'wf_state indicates stuck workflow', 
         'Active asset has in-flight or stuck workflow.',
         'Resolve workflow.', 'asset_master', None, 
         'wf_state IN (W,R,U,X) AND status="N"',
         lambda df: df['wf_state'].isin(['W', 'R', 'U', 'X']) & (df['status'] == 'N')),

        ('DQ-AM-K03', 19, 'Asset Master', 'Consistency', 'Medium',
         'org_amt_date is null but org_amount populated', 
         'Cost exists but has no date.',
         'Populate org_amt_date.', 'asset_master', None, 
         'org_amt_date IS NULL AND org_amount IS NOT NULL',
         lambda df: df['org_amt_date'].isna() & df['org_amount'].notna()),

        ('DQ-AM-K04', 19, 'Asset Master', 'Consistency', 'Medium',
         'grant_flag = 1 but no grant dim value', 
         'Grant funded but missing analytical coding.',
         'Populate dim_1.', 'asset_master', None, 
         'grant_flag = 1 AND dim_1 IS NULL',
         lambda df: (pd.to_numeric(df['grant_flag'], errors='coerce') == 1) & df['dim_1'].isna()),

        ('DQ-AM-D01', 19, 'Asset Master', 'Uniqueness', 'Critical',
         'Duplicate asset_id within client', 
         'Primary key violation.',
         'Resolve duplicate.', 'asset_master', None, 
         'COUNT > 1',
         lambda df: df.duplicated(subset=['house', 'asset_id'], keep=False)),

        ('DQ-AM-D02', 19, 'Asset Master', 'Uniqueness', 'Medium',
         'Identical key fields within client', 
         'Potential duplicate asset entries.',
         'Review for duplication.', 'asset_master', None, 
         'COUNT > 1',
         lambda df: df.duplicated(subset=['house', 'description', 'asset_group', 'cap_date_from', 'org_amount'], keep=False)),

        ('DQ-AM-R01', 19, 'Asset Master', 'Referential Integrity', 'Critical',
         'Transaction with no matching master record', 
         'Orphaned transaction.',
         'Create master record.', 'asset_balances', 'asset_master', 
         'asset_id NOT IN master',
         lambda df, frames: ~df['asset_id'].isin(frames.get('asset_master', pd.DataFrame())['asset_id']) if 'asset_master' in frames else pd.Series(False, index=df.index)),

        ('DQ-AM-R02', 19, 'Asset Master', 'Referential Integrity', 'Critical',
         'Depreciation book with no matching master record', 
         'Orphaned depreciation book.',
         'Create master record.', 'asset_depreciation', 'asset_master', 
         'asset_id NOT IN master',
         lambda df, frames: ~df['asset_id'].isin(frames.get('asset_master', pd.DataFrame())['asset_id']) if 'asset_master' in frames else pd.Series(False, index=df.index)),

        ('DQ-AM-R03', 19, 'Asset Master', 'Referential Integrity', 'High',
         'Active transaction against inactive master', 
         'Active financial activity against closed asset.',
         'Review asset status.', 'asset_balances', 'asset_master', 
         'master.status NOT IN (N, T)',
         lambda df, frames: df['asset_id'].isin(frames.get('asset_master', pd.DataFrame()).query('status not in ["N", "T"]')['asset_id']) if 'asset_master' in frames else pd.Series(False, index=df.index)),

        ('DQ-AM-R04', 19, 'Asset Master', 'Referential Integrity', 'High',
         'parent_asset does not match active asset in extract', 
         'Child references closed or missing parent.',
         'Review parent_asset.', 'asset_master', 'asset_master', 
         'parent_asset NOT IN master',
         lambda df, frames: df['parent_asset'].notna() & ~df['parent_asset'].isin(frames.get('asset_master', pd.DataFrame())['asset_id']) if 'asset_master' in frames else pd.Series(False, index=df.index)),

        ('DQ-AM-R05', 19, 'Asset Master', 'Referential Integrity', 'Medium',
         'apar_id does not match supplier master', 
         'Broken procurement link.',
         'Review apar_id.', 'asset_master', 'asuheader', 
         'apar_id NOT IN asuheader',
         lambda df, frames: df['apar_id'].notna() & ~df['apar_id'].isin(frames.get('asuheader', pd.DataFrame())['apar_id']) if 'asuheader' in frames else pd.Series(False, index=df.index)),

        # ======================================================================
        # --- ASSET DEPRECIATION (asset_depreciation) ---
        # ======================================================================
        ('DQ-AD-C01', 19, 'Asset Depreciation', 'Completeness', 'Critical',
         'asset_id is null or blank', 
         'No depreciation book can exist without asset reference.',
         'Populate asset_id.', 'asset_depreciation', None, 
         'asset_id IS NULL',
         lambda df: df['asset_id'].isna() | (df['asset_id'] == '')),

        ('DQ-AD-C02', 19, 'Asset Depreciation', 'Completeness', 'Critical',
         'depr_book_id is null or blank', 
         'Primary key component missing.',
         'Populate depr_book_id.', 'asset_depreciation', None, 
         'depr_book_id IS NULL',
         lambda df: df['depr_book_id'].isna() | (df['depr_book_id'] == '')),

        ('DQ-AD-C03', 19, 'Asset Depreciation', 'Completeness', 'High',
         'depr_method is null or blank', 
         'Active books must have a method.',
         'Populate depr_method.', 'asset_depreciation', None, 
         'depr_method IS NULL',
         lambda df: df['depr_method'].isna() | (df['depr_method'] == '')),

        ('DQ-AD-C04', 19, 'Asset Depreciation', 'Completeness', 'High',
         'lifetime is null or zero for LIN/SYD', 
         'Method requires useful life.',
         'Populate lifetime.', 'asset_depreciation', None, 
         'lifetime <= 0 AND method IN (LIN,SYD)',
         lambda df: df['depr_method'].isin(['LIN', 'SYD']) & (pd.to_numeric(df['lifetime'], errors='coerce').fillna(0) <= 0)),

        ('DQ-AD-C05', 19, 'Asset Depreciation', 'Completeness', 'High',
         'depr_percent is null or zero for BAL', 
         'Reducing balance requires a rate.',
         'Populate depr_percent.', 'asset_depreciation', None, 
         'depr_percent <= 0 AND method = BAL',
         lambda df: (df['depr_method'] == 'BAL') & (pd.to_numeric(df['depr_percent'], errors='coerce').fillna(0) <= 0)),

        ('DQ-AD-C06', 19, 'Asset Depreciation', 'Completeness', 'Medium',
         'cap_date_from is null but cap_flag = 1', 
         'Capitalised book needs a date.',
         'Populate cap_date_from.', 'asset_depreciation', None, 
         'cap_date_from IS NULL AND cap_flag=1',
         lambda df: df['cap_date_from'].isna() & (pd.to_numeric(df['cap_flag'], errors='coerce') == 1)),

        ('DQ-AD-C07', 19, 'Asset Depreciation', 'Completeness', 'Medium',
         'depr_period is null for active book', 
         'Suggests depreciation never run.',
         'Review depr_period.', 'asset_depreciation', None, 
         'depr_period IS NULL',
         lambda df: df['depr_period'].isna()),

        ('DQ-AD-V01', 19, 'Asset Depreciation', 'Validity', 'Critical',
         'depr_method invalid', 
         'Must map to target system method.',
         'Correct depr_method.', 'asset_depreciation', None, 
         'depr_method NOT IN (LIN,BAL,EXP,SYD)',
         lambda df: ~df['depr_method'].isin(['LIN', 'BAL', 'EXP', 'SYD'])),

        ('DQ-AD-V02', 19, 'Asset Depreciation', 'Validity', 'Critical',
         'status invalid', 
         'Unexpected status code.',
         'Correct status.', 'asset_depreciation', None, 
         'status NOT IN (N,P,C,T)',
         lambda df: ~df['status'].isin(['N', 'P', 'C', 'T'])),

        ('DQ-AD-V03', 19, 'Asset Depreciation', 'Validity', 'High',
         'depr_percent > 100', 
         'Rate above 100% is invalid.',
         'Correct depr_percent.', 'asset_depreciation', None, 
         'depr_percent > 100',
         lambda df: pd.to_numeric(df['depr_percent'], errors='coerce').fillna(0) > 100),

        ('DQ-AD-V04', 19, 'Asset Depreciation', 'Validity', 'High',
         'lifetime <= 0 for active depreciating asset', 
         'Zero or negative useful life invalid.',
         'Correct lifetime.', 'asset_depreciation', None, 
         'lifetime <= 0 AND method != EXP',
         lambda df: (df['depr_method'] != 'EXP') & (pd.to_numeric(df['lifetime'], errors='coerce').fillna(0) <= 0)),

        ('DQ-AD-V05', 19, 'Asset Depreciation', 'Timeliness', 'High',
         'date_from is after date_to', 
         'Ownership inverted.',
         'Correct dates.', 'asset_depreciation', None, 
         'date_from > date_to',
         lambda df: pd.to_datetime(df['date_from'], errors='coerce').notna() & pd.to_datetime(df['date_to'], errors='coerce').notna() & (pd.to_datetime(df['date_from'], errors='coerce') > pd.to_datetime(df['date_to'], errors='coerce'))),

        ('DQ-AD-V06', 19, 'Asset Depreciation', 'Timeliness', 'Medium',
         'cap_date_from is before date_from', 
         'Cannot be capitalised before ownership.',
         'Correct dates.', 'asset_depreciation', None, 
         'cap_date_from < date_from',
         lambda df: pd.to_datetime(df['cap_date_from'], errors='coerce').notna() & pd.to_datetime(df['date_from'], errors='coerce').notna() & (pd.to_datetime(df['cap_date_from'], errors='coerce') < pd.to_datetime(df['date_from'], errors='coerce'))),

        ('DQ-AD-V07', 19, 'Asset Depreciation', 'Validity', 'Medium',
         'depr_percent is negative', 
         'Negative rate invalid.',
         'Correct depr_percent.', 'asset_depreciation', None, 
         'depr_percent < 0',
         lambda df: pd.to_numeric(df['depr_percent'], errors='coerce').fillna(0) < 0),

        ('DQ-AD-T01', 19, 'Asset Depreciation', 'Timeliness', 'Medium',
         'last_update is in the future', 
         'System clock error.',
         'Correct date.', 'asset_depreciation', None, 
         'last_update > TODAY',
         lambda df: pd.to_datetime(df['last_update'], errors='coerce').notna() & (pd.to_datetime(df['last_update'], errors='coerce') > today)),

        ('DQ-AD-K01', 19, 'Asset Depreciation', 'Consistency', 'High',
         'date_to is populated but status is N', 
         'Active but ownership ended.',
         'Review status.', 'asset_depreciation', None, 
         'date_to IS NOT NULL AND status=N',
         lambda df: df['date_to'].notna() & (df['status'] == 'N')),

        ('DQ-AD-K02', 19, 'Asset Depreciation', 'Consistency', 'High',
         'depr_period stale', 
         'Depreciation not run recently.',
         'Review depr_period.', 'asset_depreciation', None, 
         'depr_period stale',
         lambda df: pd.to_numeric(df['depr_period'], errors='coerce').fillna(999999) < ((today.year * 100) + today.month - 3)),

        ('DQ-AD-K03', 19, 'Asset Depreciation', 'Consistency', 'Medium',
         'switch = true but method != BAL', 
         'Switch only applicable to reducing balance.',
         'Review switch.', 'asset_depreciation', None, 
         'switch=True AND method!=BAL',
         lambda df: (df['switch'] == True) & (df['depr_method'] != 'BAL')),

        ('DQ-AD-K04', 19, 'Asset Depreciation', 'Consistency', 'Medium',
         'index_id populated but method = EXP', 
         'Indexed revaluation on expensed asset.',
         'Review index_id.', 'asset_depreciation', None, 
         'index_id IS NOT NULL AND method=EXP',
         lambda df: df['index_id'].notna() & (df['depr_method'] == 'EXP')),

        ('DQ-AD-K05', 19, 'Asset Depreciation', 'Consistency', 'Medium',
         'res_value > org_amount on master', 
         'Residual value exceeds original cost.',
         'Review res_value.', 'asset_depreciation', 'asset_master', 
         'res_value > org_amount',
         lambda df, frames: pd.to_numeric(df['res_value'], errors='coerce').fillna(0) > pd.to_numeric(df['asset_id'].map(frames.get('asset_master', pd.DataFrame()).drop_duplicates('asset_id').set_index('asset_id')['org_amount']), errors='coerce').fillna(float('inf')) if 'asset_master' in frames else pd.Series(False, index=df.index)),

        ('DQ-AD-D01', 19, 'Asset Depreciation', 'Uniqueness', 'Critical',
         'Duplicate composite key', 
         'Primary key violation.',
         'Resolve duplicate.', 'asset_depreciation', None, 
         'COUNT > 1',
         lambda df: df.duplicated(subset=['house', 'asset_id', 'depr_book_id'], keep=False)),

        ('DQ-AD-X01', 19, 'Asset Depreciation', 'Referential Integrity', 'Critical',
         'Orphaned depreciation book', 
         'No matching record in asset_master.',
         'Create master record.', 'asset_depreciation', 'asset_master', 
         'asset_id NOT IN master',
         lambda df, frames: ~df['asset_id'].isin(frames.get('asset_master', pd.DataFrame())['asset_id']) if 'asset_master' in frames else pd.Series(False, index=df.index)),

        ('DQ-AD-X02', 19, 'Asset Depreciation', 'Referential Integrity', 'High',
         'Active asset with no depreciation book', 
         'Cannot calculate depreciation.',
         'Create depr book.', 'asset_master', 'asset_depreciation', 
         'asset_id NOT IN depr',
         lambda df, frames: (df['status'] == 'N') & ~df['asset_id'].isin(frames.get('asset_depreciation', pd.DataFrame())['asset_id']) if 'asset_depreciation' in frames else pd.Series(False, index=df.index)),

        ('DQ-AD-X03', 19, 'Asset Depreciation', 'Referential Integrity', 'High',
         'cap_date_from mismatch', 
         'Master and book dates differ.',
         'Align dates.', 'asset_depreciation', 'asset_master', 
         'depr.cap_date_from != master.cap_date_from',
         lambda df, frames: df['cap_date_from'] != df['asset_id'].map(frames.get('asset_master', pd.DataFrame()).drop_duplicates('asset_id').set_index('asset_id')['cap_date_from']) if 'asset_master' in frames else pd.Series(False, index=df.index)),

        ('DQ-AD-X04', 19, 'Asset Depreciation', 'Referential Integrity', 'Medium',
         'res_value > org_amount', 
         'Covered by K05.',
         'Review values.', 'asset_depreciation', 'asset_master', 
         'res_value > org_amount',
         lambda df, frames: pd.Series(False, index=df.index)),

        ('DQ-AD-X05', 19, 'Asset Depreciation', 'Referential Integrity', 'High',
         'Active book with no transactions', 
         'Never capitalised or posted.',
         'Review activity.', 'asset_depreciation', 'asset_balances', 
         'key NOT IN balances',
         lambda df, frames: ~df.set_index(['house', 'asset_id', 'depr_book_id']).index.isin(frames.get('asset_balances', pd.DataFrame()).set_index(['house', 'asset_id', 'depr_book_id']).index if 'asset_balances' in frames else [])),

        # ======================================================================
        # --- ASSET BALANCES (asset_balances) ---
        # ======================================================================
        ('DQ-AB-C01', 19, 'Asset Balances', 'Completeness', 'Critical',
         'asset_id is null', 
         'Required for aggregation.',
         'Populate asset_id.', 'asset_balances', None, 
         'asset_id IS NULL',
         lambda df: df['asset_id'].isna() | (df['asset_id'] == '')),

        ('DQ-AB-C02', 19, 'Asset Balances', 'Completeness', 'Critical',
         'depr_book_id is null', 
         'Required for aggregation.',
         'Populate depr_book_id.', 'asset_balances', None, 
         'depr_book_id IS NULL',
         lambda df: df['depr_book_id'].isna() | (df['depr_book_id'] == '')),

        ('DQ-AB-C03', 19, 'Asset Balances', 'Completeness', 'Critical',
         'trans_type is null', 
         'Required for logic.',
         'Populate trans_type.', 'asset_balances', None, 
         'trans_type IS NULL',
         lambda df: df['trans_type'].isna() | (df['trans_type'] == '')),

        ('DQ-AB-C04', 19, 'Asset Balances', 'Completeness', 'High',
         'total_amount is null', 
         'Value must exist.',
         'Review aggregation.', 'asset_balances', None, 
         'total_amount IS NULL',
         lambda df: df['total_amount'].isna()),

        ('DQ-AB-V01', 19, 'Asset Balances', 'Validity', 'Critical',
         'trans_type invalid', 
         'Outside expected set.',
         'Correct trans_type.', 'asset_balances', None, 
         'trans_type NOT IN (...)',
         lambda df: ~df['trans_type'].isin(['CA','PC','SA','ND','ED','FD','VN','RV','ZU'])),

        ('DQ-AB-V02', 19, 'Asset Balances', 'Validity', 'High',
         'total_amount = 0 for CA', 
         'Zero cost capitalisation.',
         'Review amount.', 'asset_balances', None, 
         'trans_type=CA AND total_amount=0',
         lambda df: (df['trans_type'] == 'CA') & (pd.to_numeric(df['total_amount'], errors='coerce').fillna(0) == 0)),

        ('DQ-AB-V03', 19, 'Asset Balances', 'Timeliness', 'Medium',
         'max_trans_date in future', 
         'Data entry error.',
         'Correct date.', 'asset_balances', None, 
         'max_trans_date > TODAY',
         lambda df: pd.to_datetime(df.get('max_trans_date', pd.Series(index=df.index)), errors='coerce').notna() & (pd.to_datetime(df.get('max_trans_date', pd.Series(index=df.index)), errors='coerce') > today)),

        ('DQ-AB-K01', 19, 'Asset Balances', 'Consistency', 'High',
         'Derived NBV is negative', 
         'Accumulated depr exceeds cost.',
         'Review balance.', 'asset_balances', None, 
         'NBV < 0',
         lambda df: df.index.isin(df.groupby(['house', 'asset_id', 'depr_book_id']).filter(lambda g: (g[g['trans_type'].isin(['CA','PC','VN','ZU'])]['total_amount'].sum() - g[g['trans_type'].isin(['ND','ED','FD','SA'])]['total_amount'].sum()) < 0).index)),

        ('DQ-AB-K02', 19, 'Asset Balances', 'Consistency', 'High',
         'Disposal without capitalisation', 
         'SA row but no CA row.',
         'Review history.', 'asset_balances', None, 
         'SA exists, CA missing',
         lambda df: df.index.isin(df.groupby(['house', 'asset_id', 'depr_book_id']).filter(lambda g: ('SA' in g['trans_type'].values) and ('CA' not in g['trans_type'].values)).index)),

        ('DQ-AB-K03', 19, 'Asset Balances', 'Consistency', 'High',
         'Depreciation without capitalisation', 
         'ND/ED/FD exists, no CA.',
         'Review history.', 'asset_balances', None, 
         'Depr exists, CA missing',
         lambda df: df.index.isin(df.groupby(['house', 'asset_id', 'depr_book_id']).filter(lambda g: g['trans_type'].isin(['ND','ED','FD']).any() and ('CA' not in g['trans_type'].values)).index)),

        ('DQ-AB-K04', 19, 'Asset Balances', 'Consistency', 'Low',
         'NBV=0 and no disposal', 
         'Fully depreciated but active.',
         'Review asset.', 'asset_balances', None, 
         'NBV=0 AND no SA',
         lambda df: pd.Series(False, index=df.index)),

        ('DQ-AB-K05', 19, 'Asset Balances', 'Consistency', 'Low',
         'No depreciation for depreciating asset', 
         'Processing gap.',
         'Review asset.', 'asset_balances', 'asset_depreciation', 
         'No ND/ED/FD',
         lambda df: pd.Series(False, index=df.index)),

        ('DQ-AB-X01', 19, 'Asset Balances', 'Referential Integrity', 'Critical',
         'Orphaned balance', 
         'No master record.',
         'Create master.', 'asset_balances', 'asset_master', 
         'asset_id NOT IN master',
         lambda df, frames: ~df['asset_id'].isin(frames.get('asset_master', pd.DataFrame())['asset_id']) if 'asset_master' in frames else pd.Series(False, index=df.index)),

        ('DQ-AB-X02', 19, 'Asset Balances', 'Referential Integrity', 'Critical',
         'Balance for missing book', 
         'No depr book record.',
         'Create depr book.', 'asset_balances', 'asset_depreciation', 
         'key NOT IN depr',
         lambda df, frames: ~df.set_index(['house', 'asset_id', 'depr_book_id']).index.isin(frames.get('asset_depreciation', pd.DataFrame()).set_index(['house', 'asset_id', 'depr_book_id']).index if 'asset_depreciation' in frames else []),),

        ('DQ-AB-X03', 19, 'Asset Balances', 'Referential Integrity', 'High',
         'Active asset with no balances', 
         'Never capitalised.',
         'Review history.', 'asset_master', 'asset_balances', 
         'asset_id NOT IN balances',
         lambda df, frames: (df['status'] == 'N') & ~df['asset_id'].isin(frames.get('asset_balances', pd.DataFrame())['asset_id']) if 'asset_balances' in frames else pd.Series(False, index=df.index)),

        ('DQ-AB-X04', 19, 'Asset Balances', 'Referential Integrity', 'Critical',
         'Reconcile NBV to GL', 
         'Primary migration check.',
         'Reconcile GL.', 'asset_balances', 'gl_opening_balances', 
         'NBV != GL Fixed Assets',
         lambda df: pd.Series(False, index=df.index)),

        # ======================================================================
        # --- ASSET TRANS FLAGS (asset_trans_flags) ---
        # ======================================================================
        ('DQ-AF-X01', 19, 'Asset Trans Flags', 'Referential Integrity', 'High',
         'SA transaction on active asset', 
         'Disposal posted but asset still active.',
         'Update master.', 'asset_trans_flags', 'asset_master', 
         'trans_type=SA AND master.status=N',
         lambda df, frames: (df['trans_type'] == 'SA') & df['asset_id'].isin(frames.get('asset_master', pd.DataFrame()).query('status == "N"')['asset_id']) if 'asset_master' in frames else pd.Series(False, index=df.index)),

        ('DQ-AF-X02', 19, 'Asset Trans Flags', 'Referential Integrity', 'High',
         'Depreciation posted after date_to', 
         'Posted after ownership ended.',
         'Review dates.', 'asset_trans_flags', 'asset_master', 
         'trans_type IN (ND,ED,FD) AND trans_date > master.date_to',
         lambda df, frames: (df['trans_type'].isin(['ND', 'ED', 'FD'])) & pd.to_datetime(df['trans_date'], errors='coerce').notna() & (pd.to_datetime(df['trans_date'], errors='coerce') > pd.to_datetime(df['asset_id'].map(frames.get('asset_master', pd.DataFrame()).drop_duplicates('asset_id').set_index('asset_id')['date_to']), errors='coerce')) if 'asset_master' in frames else pd.Series(False, index=df.index)),

        ('DQ-AF-X03', 19, 'Asset Trans Flags', 'Consistency', 'High',
         'CA transaction with zero amount', 
         'Zero cost capitalisation at row level.',
         'Review amount.', 'asset_trans_flags', None, 
         'trans_type=CA AND amount=0',
         lambda df: (df['trans_type'] == 'CA') & (pd.to_numeric(df['amount'], errors='coerce').fillna(0) == 0)),

        ('DQ-AF-X04', 19, 'Asset Trans Flags', 'Timeliness', 'High',
         'trans_date in future', 
         'Data entry error.',
         'Correct trans_date.', 'asset_trans_flags', None, 
         'trans_date > TODAY',
         lambda df: pd.to_datetime(df['trans_date'], errors='coerce').notna() & (pd.to_datetime(df['trans_date'], errors='coerce') > today)),

        ('DQ-AF-X05', 19, 'Asset Trans Flags', 'Consistency', 'Medium',
         'Multiple CA transactions', 
         'More than one capitalisation event.',
         'Review capitalisation.', 'asset_trans_flags', None, 
         'COUNT(CA) > 1',
         lambda df: df.index.isin(df[df['trans_type'] == 'CA'].groupby(['house', 'asset_id', 'depr_book_id']).filter(lambda g: len(g) > 1).index)),
    ]
    return checks
