-- =============================================================================
-- asset_trans_flags.sql
-- Houses of Parliament — Finance Systems Programme
-- Fixed Asset Transaction Flags Extract (Hybrid: Individual + Aggregated)
-- Migration scope: DQ checks only — not a migration input
-- Source table: aattrans (filtered, narrow)
-- =============================================================================
--
-- INSTANCE & CLIENT
-- Run the HOC/HOL run files separately, not this spec file.
-- HoC: Agresso_HoC, clients CA and CM → asset_trans_flags_HOC.csv
-- HoL: agresso_HoL, client LA          → asset_trans_flags_HOL.csv
--
-- PURPOSE
-- This extract exists solely to support DQ consistency checks that require
-- row-level or latest-date transaction data. It is not used for balance
-- derivation (handled by asset_balances.sql) and is not a migration input.
--
-- WHY THE VOLUME PROBLEM
-- aattrans has one row per transaction line. A monthly-depreciated asset
-- capitalised ten years ago has 120+ ND rows per depreciation book alone.
-- At Parliament scale this runs to millions of rows even with type filters
-- and fiscal year windows. The key insight is that the DQ check for
-- depreciation anomalies (DQ-AF-X02) only needs to know the LATEST
-- depreciation date per asset/book — not every individual ND row.
--
-- HYBRID DESIGN: INDIVIDUAL + AGGREGATED
-- The extract is a UNION ALL of two parts:
--
--   Part 1 — Individual rows for CA and SA (low volume, date detail needed):
--     CA: needed for zero-cost capitalisation check (DQ-AF-X03) and
--         multiple capitalisation check (DQ-AF-X05). Every CA row matters.
--     SA: needed for disposal-on-active-asset check (DQ-AF-X01). Every
--         SA transaction date and amount must be surfaced.
--
--   Part 2 — Aggregated MAX(trans_date) per (client, asset_id, depr_book_id,
--             trans_type) for ND, ED, FD (collapses millions to thousands):
--     DQ-AF-X02 only needs to know whether ANY depreciation was posted after
--     date_to. MAX(trans_date) is sufficient — if the latest depreciation
--     date is within the valid window, all earlier ones are too.
--     DQ-AF-X04 (future-dated) is also satisfied by MAX(trans_date) since
--     if the latest posting is not future-dated, none are.
--
-- row_type column distinguishes the two parts in Python:
--   'INDIVIDUAL'  — CA or SA, one row per transaction
--   'LATEST_DEPR' — ND/ED/FD, one row per (client, asset_id, book, type),
--                   trans_date = MAX(trans_date), amount and dc_flag = NULL
--
-- CHECKS SUPPORTED
-- DQ-AF-X01: filter to SA rows (row_type='INDIVIDUAL'), join asset_master,
--            flag where status = 'N'
-- DQ-AF-X02: filter to ND/ED/FD rows (row_type='LATEST_DEPR'), join
--            asset_master, flag where trans_date > date_to
-- DQ-AF-X03: filter to CA rows (row_type='INDIVIDUAL'), flag where amount
--            = 0 or null
-- DQ-AF-X04: all rows, flag where trans_date > today. MAX(trans_date) in
--            aggregated rows still catches any future-dated depreciation.
-- DQ-AF-X05: filter to CA rows (row_type='INDIVIDUAL'), count per
--            (client, asset_id, depr_book_id), flag where count > 1
--
-- RELATIONSHIP TO OTHER EXTRACTS
-- Joined to asset_master in Python on (client, asset_id) for DQ-AF-X01/X02.
-- Independent of asset_balances.sql.
--
-- ASSUMPTIONS
-- A1. DQ-AF-X02 can be answered by MAX(trans_date) — if the latest depr
--     posting is within the valid window, all prior ones are too.
-- A2. amount sign convention for CA records must be confirmed with Parliament.
--     CA with amount = 0 is flagged but may be valid for donated/grant assets.
-- A3. No fiscal year window applied to CA or SA (low volume). ND/ED/FD are
--     aggregated to one row per (asset, book, type) across all history —
--     the fiscal year window on individual rows was no longer needed once
--     aggregation was applied.
-- A4. This extract does not replace asset_balances.sql for balance derivation.
--
-- =============================================================================
-- DATA QUALITY TESTS (all executed in Python against the CSV output)
-- =============================================================================
--
-- DQ-AF-X01 [High]      SA transaction exists for an asset_id where
--            asset_master status = 'N' (active asset with a disposal posting).
--            Either the master has not been updated post-disposal or the SA
--            was posted in error. Produce a list of affected assets with
--            the SA trans_date and amount for Parliament to review.
--            Join: asset_master on (client, asset_id).
--
-- DQ-AF-X02 [High]      Latest ND, ED, or FD trans_date is after
--            asset_master date_to for the same asset_id.
--            Depreciation posted after ownership ended. The asset should have
--            been closed before further depreciation was run.
--            Uses MAX(trans_date) from aggregated depr rows.
--            Join: asset_master on (client, asset_id).
--
-- DQ-AF-X03 [High]      CA transaction with amount = 0 or null.
--            Zero-cost capitalisation at row level. Not valid for standard
--            purchased assets. Surface each instance with asset_id, client,
--            and trans_date for Parliament to confirm whether legitimate
--            (donated/grant asset) or an error.
--
-- DQ-AF-X04 [High]      trans_date is in the future (beyond today's date)
--            for any row in this extract. MAX(trans_date) in aggregated depr
--            rows is sufficient to catch any future-dated depreciation posting.
--
-- DQ-AF-X05 [Medium]    Multiple CA transactions for the same
--            (client, asset_id, depr_book_id).
--            More than one capitalisation event on the same asset and book.
--            May be valid for assets capitalised in stages — flag for
--            Parliament to confirm rather than treat as an error.
--
-- =============================================================================
--
-- See asset_trans_flags_HOC_run.sql and asset_trans_flags_HOL_run.sql
-- for the run-ready versions with client filters.
